groups:
  - name: example-alerts
    rules:
      - alert: HighCPU
        expr: instance:cpu_utilization:percent > 85
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "CPU usage is above 85%"
