groups:
  - name: system_utilization
    rules:
      - record: instance:cpu_utilization:percent
        expr: 100 * (1 - avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])))

      - record: instance:memory_available:percent
        expr: 100 * node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes

      - record: instance:disk_usage:bytes
        expr: node_filesystem_size_bytes - node_filesystem_free_bytes

      - record: instance:disk_usage:percent
        expr: 100 * (1 - node_filesystem_free_bytes / node_filesystem_size_bytes)

      - record: instance:disk_used_percent
        expr: 100 * (1 - node_filesystem_free_bytes / node_filesystem_size_bytes)

