global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node' #pre-built exporter https://github.com/prometheus/node_exporter (no need for custom file)
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'gpu_fake'
    static_configs:
      - targets: ['gpu-exporter:8000']
